### PR TITLE
Edit AboutUs-Yong Zhe

### LINKED ISSUE #25: About Us Yong Zhe

### PR DESCRIPTION
**Pull request by Reallyeasy1**
Closes #25

### CODE REVIEW

**Comment by Reallyeasy1** [comment]
Closes #25

**Comment by SamsonChew** [comment]
LGTM!

**Comment by SamsonChew** [comment]
Have merge conflicts, please check AboutUs.md. Thanks!

**Comment by SamsonChew** [comment]
LGTM!

**Pull request merged**
